substitutions:
  device_name: esp32c6-supermini-1
  friendly_name: ESP32C6 SuperMini 1
  status_led_pin: GPIO15
  rgb_led_pin: GPIO8

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
  level: WARN

packages:
  wifi: !include ../packages/connectivity/wifi.yaml
  api: !include ../packages/connectivity/api.yaml
  ota: !include ../packages/connectivity/ota.yaml

sensor:
  - platform: internal_temperature
    name: "${friendly_name} Internal Temperature"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"

output:
  - platform: gpio
    id: status_led_output
    pin: ${status_led_pin}

light:
  - platform: binary
    id: status_led
    name: "${friendly_name} Status LED"
    output: status_led_output

  - platform: esp32_rmt_led_strip
    id: rgb_led
    name: "${friendly_name} RGB LED"
    pin: ${rgb_led_pin}
    num_leds: 1
    chipset: WS2812
    rgb_order: GRB
    default_transition_length: 200ms
    restore_mode: RESTORE_DEFAULT_OFF
