substitutions:
  device_name: esp32c3-device1
  friendly_name: Device1

esphome:
  name: ${device_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:
  level: WARN

packages:
  wifi: !include ../packages/connectivity/wifi.yaml
  api: !include ../packages/connectivity/api.yaml
  ota: !include ../packages/connectivity/ota.yaml

sensor:
  - platform: internal_temperature
    name: "${friendly_name} Internal Temperature"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
    name: "${friendly_name} Button"
